annotations:
  screwdriver.cd/chainPR : true

parameters:
    user: "jithine 1"
    region: "us-west-1"
    az:
        value: "1"
        description: "default availability zones"

shared:
  image: node:12
  steps:
        - nothing: echo 'nothing'
        - sleep: sleep $SLEEP_TIME
  environment:
    USER_SHELL_BIN: "/bin/bash"
    SD_ZIP_ARTIFACTS: false
    SD_COVERAGE_PLUGIN_ENABLED: false
    SLEEP_TIME: 15

  annotations:
    screwdriver.cd/collapseBuilds: false
    e2e_test_ui: &e2e_test_ui
      requires: [ component_build_deploy_publish ]

jobs:
  hotfix_release:
    steps:
      - nothing: |
          echo "Setting meta data variable 'hotfix_release' to 'true'"
          meta set hotfix_release "true"

  lint:
    requires: [~commit, ~hotfix_release, ~pr]
    steps:
      - sleep: sleep 10

  build_test:
    environment:
      SD_COVERAGE_PLUGIN_ENABLED: true
    requires: [~commit, ~hotfix_release, ~pr]
    steps:
      - sleep: sleep 200

  component_build_deploy_publish:
    requires: [~commit, hotfix_release, ~pr]

  bucket_1_ui:
    <<: *e2e_test_ui
    steps:
        - sleep: sleep 5
        - fail-maybe: if [ "$(meta get parameters.az.value)" -eq "1" ]; then false; else true; fi 

  bucket_2_ui:
    <<: *e2e_test_ui

  bucket_3_ui:
    <<: *e2e_test_ui

  bucket_4_ui:
    <<: *e2e_test_ui

  # Certifcation section
  certify_tag:
    requires: [bucket_1_ui, bucket_2_ui, bucket_3_ui, bucket_4_ui, lint, build_test]
